version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12345:12345"
    depends_on:
      - redis
    environment: # Pass environment variables to the service
      REDIS_URL: redis:6379  
    networks:
      - backend

  redis:
    image: "redis:alpine" # Use a public Redis image to build the redis service    
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:    